/** English region lookup generated from countryCodes with Node Intl.DisplayNames. Avoids constructing every display name during browser hydration. */
export const countryRegions: Readonly<Record<string, string>> = {
  ad: "ad",
  andorra: "ad",
  ae: "ae",
  "united arab emirates": "ae",
  af: "af",
  afghanistan: "af",
  ag: "ag",
  "antigua barbuda": "ag",
  ai: "ai",
  anguilla: "ai",
  al: "al",
  albania: "al",
  am: "am",
  armenia: "am",
  ao: "ao",
  angola: "ao",
  aq: "aq",
  antarctica: "aq",
  ar: "ar",
  argentina: "ar",
  as: "as",
  "american samoa": "as",
  at: "at",
  austria: "at",
  au: "au",
  australia: "au",
  aw: "aw",
  aruba: "aw",
  ax: "ax",
  "aland islands": "ax",
  az: "az",
  azerbaijan: "az",
  ba: "ba",
  "bosnia herzegovina": "ba",
  bb: "bb",
  barbados: "bb",
  bd: "bd",
  bangladesh: "bd",
  be: "be",
  belgium: "be",
  bf: "bf",
  "burkina faso": "bf",
  bg: "bg",
  bulgaria: "bg",
  bh: "bh",
  bahrain: "bh",
  bi: "bi",
  burundi: "bi",
  bj: "bj",
  benin: "bj",
  bl: "bl",
  "st barthelemy": "bl",
  bm: "bm",
  bermuda: "bm",
  bn: "bn",
  brunei: "bn",
  bo: "bo",
  bolivia: "bo",
  bq: "bq",
  "caribbean netherlands": "bq",
  br: "br",
  brazil: "br",
  bs: "bs",
  bahamas: "bs",
  bt: "bt",
  bhutan: "bt",
  bv: "bv",
  "bouvet island": "bv",
  bw: "bw",
  botswana: "bw",
  by: "by",
  belarus: "by",
  bz: "bz",
  belize: "bz",
  ca: "ca",
  canada: "ca",
  cc: "cc",
  "cocos keeling islands": "cc",
  cd: "cd",
  "congo kinshasa": "cd",
  cf: "cf",
  "central african republic": "cf",
  cg: "cg",
  "congo brazzaville": "cg",
  ch: "ch",
  switzerland: "ch",
  ci: "ci",
  "cote d ivoire": "ci",
  ck: "ck",
  "cook islands": "ck",
  cl: "cl",
  chile: "cl",
  cm: "cm",
  cameroon: "cm",
  cn: "cn",
  china: "cn",
  co: "co",
  colombia: "co",
  cr: "cr",
  "costa rica": "cr",
  cu: "cu",
  cuba: "cu",
  cv: "cv",
  "cape verde": "cv",
  cw: "cw",
  curacao: "cw",
  cx: "cx",
  "christmas island": "cx",
  cy: "cy",
  cyprus: "cy",
  cz: "cz",
  czechia: "cz",
  de: "de",
  germany: "de",
  dj: "dj",
  djibouti: "dj",
  dk: "dk",
  denmark: "dk",
  dm: "dm",
  dominica: "dm",
  do: "do",
  "dominican republic": "do",
  dz: "dz",
  algeria: "dz",
  ec: "ec",
  ecuador: "ec",
  ee: "ee",
  estonia: "ee",
  eg: "eg",
  egypt: "eg",
  eh: "eh",
  "western sahara": "eh",
  er: "er",
  eritrea: "er",
  es: "es",
  spain: "es",
  et: "et",
  ethiopia: "et",
  fi: "fi",
  finland: "fi",
  fj: "fj",
  fiji: "fj",
  fk: "fk",
  "falkland islands": "fk",
  fm: "fm",
  micronesia: "fm",
  fo: "fo",
  "faroe islands": "fo",
  fr: "fr",
  france: "fr",
  ga: "ga",
  gabon: "ga",
  gb: "gb",
  "united kingdom": "gb",
  gd: "gd",
  grenada: "gd",
  ge: "ge",
  georgia: "ge",
  gf: "gf",
  "french guiana": "gf",
  gg: "gg",
  guernsey: "gg",
  gh: "gh",
  ghana: "gh",
  gi: "gi",
  gibraltar: "gi",
  gl: "gl",
  greenland: "gl",
  gm: "gm",
  gambia: "gm",
  gn: "gn",
  guinea: "gn",
  gp: "gp",
  guadeloupe: "gp",
  gq: "gq",
  "equatorial guinea": "gq",
  gr: "gr",
  greece: "gr",
  gs: "gs",
  "south georgia south sandwich islands": "gs",
  gt: "gt",
  guatemala: "gt",
  gu: "gu",
  guam: "gu",
  gw: "gw",
  "guinea bissau": "gw",
  gy: "gy",
  guyana: "gy",
  hk: "hk",
  "hong kong sar china": "hk",
  hm: "hm",
  "heard mcdonald islands": "hm",
  hn: "hn",
  honduras: "hn",
  hr: "hr",
  croatia: "hr",
  ht: "ht",
  haiti: "ht",
  hu: "hu",
  hungary: "hu",
  id: "id",
  indonesia: "id",
  ie: "ie",
  ireland: "ie",
  il: "il",
  israel: "il",
  im: "im",
  "isle of man": "im",
  in: "in",
  india: "in",
  io: "io",
  "british indian ocean territory": "io",
  iq: "iq",
  iraq: "iq",
  ir: "ir",
  iran: "ir",
  is: "is",
  iceland: "is",
  it: "it",
  italy: "it",
  je: "je",
  jersey: "je",
  jm: "jm",
  jamaica: "jm",
  jo: "jo",
  jordan: "jo",
  jp: "jp",
  japan: "jp",
  ke: "ke",
  kenya: "ke",
  kg: "kg",
  kyrgyzstan: "kg",
  kh: "kh",
  cambodia: "kh",
  ki: "ki",
  kiribati: "ki",
  km: "km",
  comoros: "km",
  kn: "kn",
  "st kitts nevis": "kn",
  kp: "kp",
  "north korea": "kp",
  kr: "kr",
  "south korea": "kr",
  kw: "kw",
  kuwait: "kw",
  ky: "ky",
  "cayman islands": "ky",
  kz: "kz",
  kazakhstan: "kz",
  la: "la",
  laos: "la",
  lb: "lb",
  lebanon: "lb",
  lc: "lc",
  "st lucia": "lc",
  li: "li",
  liechtenstein: "li",
  lk: "lk",
  "sri lanka": "lk",
  lr: "lr",
  liberia: "lr",
  ls: "ls",
  lesotho: "ls",
  lt: "lt",
  lithuania: "lt",
  lu: "lu",
  luxembourg: "lu",
  lv: "lv",
  latvia: "lv",
  ly: "ly",
  libya: "ly",
  ma: "ma",
  morocco: "ma",
  mc: "mc",
  monaco: "mc",
  md: "md",
  moldova: "md",
  me: "me",
  montenegro: "me",
  mf: "mf",
  "st martin": "mf",
  mg: "mg",
  madagascar: "mg",
  mh: "mh",
  "marshall islands": "mh",
  mk: "mk",
  "north macedonia": "mk",
  ml: "ml",
  mali: "ml",
  mm: "mm",
  "myanmar burma": "mm",
  mn: "mn",
  mongolia: "mn",
  mo: "mo",
  "macao sar china": "mo",
  mp: "mp",
  "northern mariana islands": "mp",
  mq: "mq",
  martinique: "mq",
  mr: "mr",
  mauritania: "mr",
  ms: "ms",
  montserrat: "ms",
  mt: "mt",
  malta: "mt",
  mu: "mu",
  mauritius: "mu",
  mv: "mv",
  maldives: "mv",
  mw: "mw",
  malawi: "mw",
  mx: "mx",
  mexico: "mx",
  my: "my",
  malaysia: "my",
  mz: "mz",
  mozambique: "mz",
  na: "na",
  namibia: "na",
  nc: "nc",
  "new caledonia": "nc",
  ne: "ne",
  niger: "ne",
  nf: "nf",
  "norfolk island": "nf",
  ng: "ng",
  nigeria: "ng",
  ni: "ni",
  nicaragua: "ni",
  nl: "nl",
  netherlands: "nl",
  no: "no",
  norway: "no",
  np: "np",
  nepal: "np",
  nr: "nr",
  nauru: "nr",
  nu: "nu",
  niue: "nu",
  nz: "nz",
  "new zealand": "nz",
  om: "om",
  oman: "om",
  pa: "pa",
  panama: "pa",
  pe: "pe",
  peru: "pe",
  pf: "pf",
  "french polynesia": "pf",
  pg: "pg",
  "papua new guinea": "pg",
  ph: "ph",
  philippines: "ph",
  pk: "pk",
  pakistan: "pk",
  pl: "pl",
  poland: "pl",
  pm: "pm",
  "st pierre miquelon": "pm",
  pn: "pn",
  "pitcairn islands": "pn",
  pr: "pr",
  "puerto rico": "pr",
  ps: "ps",
  "palestinian territories": "ps",
  pt: "pt",
  portugal: "pt",
  pw: "pw",
  palau: "pw",
  py: "py",
  paraguay: "py",
  qa: "qa",
  qatar: "qa",
  re: "re",
  reunion: "re",
  ro: "ro",
  romania: "ro",
  rs: "rs",
  serbia: "rs",
  ru: "ru",
  russia: "ru",
  rw: "rw",
  rwanda: "rw",
  sa: "sa",
  "saudi arabia": "sa",
  sb: "sb",
  "solomon islands": "sb",
  sc: "sc",
  seychelles: "sc",
  sd: "sd",
  sudan: "sd",
  se: "se",
  sweden: "se",
  sg: "sg",
  singapore: "sg",
  sh: "sh",
  "st helena": "sh",
  si: "si",
  slovenia: "si",
  sj: "sj",
  "svalbard jan mayen": "sj",
  sk: "sk",
  slovakia: "sk",
  sl: "sl",
  "sierra leone": "sl",
  sm: "sm",
  "san marino": "sm",
  sn: "sn",
  senegal: "sn",
  so: "so",
  somalia: "so",
  sr: "sr",
  suriname: "sr",
  ss: "ss",
  "south sudan": "ss",
  st: "st",
  "sao tome principe": "st",
  sv: "sv",
  "el salvador": "sv",
  sx: "sx",
  "sint maarten": "sx",
  sy: "sy",
  syria: "sy",
  sz: "sz",
  eswatini: "sz",
  tc: "tc",
  "turks caicos islands": "tc",
  td: "td",
  chad: "td",
  tf: "tf",
  "french southern territories": "tf",
  tg: "tg",
  togo: "tg",
  th: "th",
  thailand: "th",
  tj: "tj",
  tajikistan: "tj",
  tk: "tk",
  tokelau: "tk",
  tl: "tl",
  "timor leste": "tl",
  tm: "tm",
  turkmenistan: "tm",
  tn: "tn",
  tunisia: "tn",
  to: "to",
  tonga: "to",
  tr: "tr",
  turkiye: "tr",
  tt: "tt",
  "trinidad tobago": "tt",
  tv: "tv",
  tuvalu: "tv",
  tw: "tw",
  taiwan: "tw",
  tz: "tz",
  tanzania: "tz",
  ua: "ua",
  ukraine: "ua",
  ug: "ug",
  uganda: "ug",
  um: "um",
  "u s outlying islands": "um",
  us: "us",
  "united states": "us",
  uy: "uy",
  uruguay: "uy",
  uz: "uz",
  uzbekistan: "uz",
  va: "va",
  "vatican city": "va",
  vc: "vc",
  "st vincent grenadines": "vc",
  ve: "ve",
  venezuela: "ve",
  vg: "vg",
  "british virgin islands": "vg",
  vi: "vi",
  "u s virgin islands": "vi",
  vn: "vn",
  vietnam: "vn",
  vu: "vu",
  vanuatu: "vu",
  wf: "wf",
  "wallis futuna": "wf",
  ws: "ws",
  samoa: "ws",
  ye: "ye",
  yemen: "ye",
  yt: "yt",
  mayotte: "yt",
  za: "za",
  "south africa": "za",
  zm: "zm",
  zambia: "zm",
  zw: "zw",
  zimbabwe: "zw",
};
