import Link from 'next/link';
import {connection} from 'next/server';
import {InformationShell} from '@/components/site/information-page';
import {DataDisclosure,validAsOf} from '@/components/site/data-disclosure';
import {priceBreakdown,type PriceRow} from '@/lib/commerce/price-breakdown';
import {pageMetadata} from '@/lib/seo/page-metadata';
import {facetMetadata} from '@/lib/seo/facets';
import type {SearchParams} from '@/lib/commerce/marketplace-query';
const usd=(cents:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(cents/100);
export async function generateMetadata({searchParams}:{searchParams:Promise<SearchParams>}) {const data=await priceBreakdown().catch(()=>null);return pageMetadata({title:'Guest Post Prices by Niche, DA and Country',description:'Dated catalogue placement prices: medians, 25th and 75th percentiles by niche, DA and country, with traffic coverage and methodology.',...facetMetadata('/guest-post-prices/',await searchParams),...(!validAsOf(data?.asOf)?{robots:{index:false,follow:true}}:{})},'/guest-post-prices/');}
function PriceTable({title,rows}:{title:string;rows:PriceRow[]}) {if(!rows.length)return null;return <section className="reference-card"><h2>{title}</h2><div className="directory-table-wrap"><table className="directory-table"><caption>{title}: USD placement prices</caption><thead><tr><th scope="col">Group</th><th scope="col">Listings</th><th scope="col">Median</th><th scope="col">25th percentile</th><th scope="col">75th percentile</th></tr></thead><tbody>{rows.map(row=><tr key={row.label}><th scope="row">{row.label}</th><td>{row.count.toLocaleString('en-US')}</td><td>{usd(row.medianCents)}</td><td>{usd(row.lowCents)}</td><td>{usd(row.highCents)}</td></tr>)}</tbody></table></div></section>;}
export default async function Page(){await connection();const result=await priceBreakdown().catch(()=>null);const data=validAsOf(result?.asOf)?result:null;
const summary=data && data.medianCents!==null?`Across ${data.total.toLocaleString('en-US')} active USD-priced listings, the median placement price is ${usd(data.medianCents)}. Traffic estimates are supplied for ${data.withTraffic.toLocaleString('en-US')} listings (${data.total ? (100*data.withTraffic/data.total).toFixed(1) : '0'}%). These figures are owner-supplied, not independently verified, as of ${data.asOf!.slice(0,10)}; writing and other campaign costs are separate.`:'Compare publication placement prices by niche, authority band and listing country. A dated distribution is unavailable at present; individual listings remain available in the marketplace.';
return <InformationShell path="/guest-post-prices/" title="Guest post prices by niche and metric" label="Catalogue price data" description={summary} active="guides" image="/02_content_metrics_panel.png">
{data && <><DataDisclosure asOf={data.asOf}/><PriceTable title="Prices by niche" rows={data.byTopic}/><PriceTable title="Prices by Domain Authority band" rows={data.byDa}/><PriceTable title="Prices by listing country" rows={data.byCountry}/><PriceTable title="Prices by Domain Rating band" rows={data.byDr}/></>}
<section className="reference-card"><h2>Methodology and refresh</h2><p>The report selects active listings from committed imports, plus active records without an import, with a numeric nonnegative USD placement price. Each record is counted once. Country and topic groups omit missing values; topic groups also omit generic categories. DA uses bands 1–9, 10–19 through 90–100; DR uses 0–19, 20–49, 50–69 and 70–100. Records without a valid score are excluded from that score’s grouping.</p><p>The median is the middle sorted price, or the mean of the two middle prices. Each percentile selects the zero-based sorted index floor(record count × percentile), capped at the final index. Groups with fewer than 15 records are omitted. Traffic coverage counts supplied numeric nonnegative traffic values, including zero; this does not verify measured visits.</p><p>The report refreshes on requests after a 15-minute cache period. If the database fails, the last successful snapshot may remain for up to 24 hours. The as-of date is the latest actual listing update in that snapshot, rather than the time you opened the page.</p><h2>How to interpret the figures</h2><p>These are listing prices, not completed transaction prices or quotations. A country field does not establish reader location. Topic, authority and traffic may have different providers or observation dates. Multiple listings can refer to one publisher, and group distributions do not establish why prices differ. Confirm price, writing scope, timing and sponsored-link qualification before planning a placement.</p></section>
<section className="reference-card"><h2>Compare and plan</h2><p><Link href="/guest-posting-sites/">Explore publications by niche</Link>, <Link href="/guides/guest-post-cost/">understand guest post costs</Link>, or <Link href="/guides/da-vs-dr-and-traffic/">compare DA, DR and traffic</Link>.</p></section></InformationShell>;}
