import Link from 'next/link';
import {InformationShell} from '@/components/site/information-page';
import {pageMetadata} from '@/lib/seo/page-metadata';
import {facetMetadata} from '@/lib/seo/facets';
import {organization} from '@/lib/config/organization';
import {authors,authorPath} from '@/lib/site/authors';
import {serializeJsonLd} from '@/lib/seo/json-ld';
import type {SearchParams} from '@/lib/commerce/marketplace-query';
export async function generateMetadata({searchParams}:{searchParams:Promise<SearchParams>}) {return pageMetadata({title:'About Name Retailer: Catalogue and Editorial Standards',description:'How Name Retailer sources listings, handles supplied metrics and disclosures, publishes guides, and supports placement enquiries.',...facetMetadata('/about/',await searchParams)},'/about/');}
export default function Page() {return <InformationShell path="/about/" title="About Name Retailer" label="Our marketplace and standards" description="Research publications, understand placement scope and prepare a plan with clear expectations." active="about" image="/03_listing_browser_panel.png">
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd({'@context':'https://schema.org','@type':'AboutPage',url:organization.url+'about/',name:'About Name Retailer',mainEntity:{'@id':organization.url+'#organization'}})}}/>
<div className="reference-information-sections">
<section className="reference-card"><h2>What the marketplace offers</h2><p>Compare guest-post and sponsored publication listings by topic, country, language, USD placement price and supplied metrics. Browse without an account, shortlist candidates and save a private placement plan after signing in. Article writing is a separate option where available. Online ordering and payment are unavailable; saving a plan does not reserve a placement.</p><Link href="/">Compare publication listings</Link></section>
<section className="reference-card"><h2>Where the catalogue comes from</h2><p>The catalogue uses owner-supplied publication inventory. Imports are checked for valid fields and conflicts before activation. These checks confirm that records can be used by the marketplace; they do not establish a publication's readership, editorial quality or ownership.</p><Link href="/methodology/">Read the catalogue methodology</Link></section>
<section className="reference-card"><h2>How metrics are handled</h2><p>Domain Authority and Domain Rating are third-party scores supplied with each listing. Traffic is an estimate. Missing metrics remain unavailable. We do not independently remeasure the entire catalogue. A listing update date is separate from a metric measurement date, and no score or placement guarantees search performance.</p><Link href="/guides/da-vs-dr-and-traffic/">Compare DA and DR</Link></section>
<section className="reference-card"><h2>Editorial standards and disclosure</h2><p>Our buying guides link to their sources and show supplied authorship and publication or update dates when available. Unknown reviewers and biographies are omitted. Paid placements should be disclosed to readers, and paid links should use sponsored or nofollow qualification. Confirm these details with the publisher before preparing content.</p><Link href="/guides/paid-guest-posts-google-link-policies/">Read the paid-link disclosure guide</Link></section>
{authors.length>0 && <section className="reference-card"><h2>Guide authors</h2><ul>{authors.map(author=><li key={author.slug}><Link href={authorPath(author)}>{author.name}</Link>{author.jobTitle ? ', '+author.jobTitle : ''}{author.bio && <p>{author.bio}</p>}</li>)}</ul></section>}
<section className="reference-card"><h2>Contact and legal entity</h2>{organization.name && <p>{organization.name}</p>}{organization.email && <p><a href={'mailto:'+organization.email}>{organization.email}</a></p>}{organization.address.streetAddress && <address>{organization.address.streetAddress}, {organization.address.addressLocality}, United Arab Emirates</address>}{organization.legalName && <p>The legal entity named in our <Link href="/privacy/">privacy policy</Link> is {organization.legalName}{organization.registeredAddress ? ', '+organization.registeredAddress : ''}.</p>}<Link href="/contact/">Contact Name Retailer about a placement</Link></section>
</div></InformationShell>;}
