import type { CatalogueStatistics } from "../commerce/catalogue-statistics";
export type BuyerGuide = {slug:string; title:string; answer:string; questions:Array<{title:string; body:string}>; table?:{columns:string[]; rows:string[][]}; sources:Array<[string,string]>; approved:boolean; author?:string; reviewer?:string; publishedAt?:string};
const google = ["Google: qualifying paid links", "https://developers.google.com/search/docs/crawling-indexing/qualify-outbound-links"] as [string,string];
const spam = ["Google: link-spam policies", "https://developers.google.com/search/docs/essentials/spam-policies#link-spam"] as [string,string];
const dr = ["Ahrefs: Domain Rating", "https://ahrefs.com/seo/glossary/domain-rating"] as [string,string];
const da = ["Moz: authority scoring guide", "https://moz-static.s3.amazonaws.com/products/landing-pages/announcements/Authority_Scoring_Guide.pdf"] as [string,string];
const traffic = ["Ahrefs: organic traffic estimation", "https://help.ahrefs.com/en/articles/1863206-what-is-organic-traffic-in-ahrefs-and-how-do-we-calculate-it"] as [string,string];
// TODO(owner): approve these scaffolds and supply author/reviewer/original publication dates.
export const buyerGuides: BuyerGuide[] = [
 {slug:"guest-post-cost",title:"How much does a guest post cost?",answer:"",approved:false,sources:[google,spam],questions:[{title:"What do the catalogue prices show?",body:"The snapshot below covers active publications and their supplied USD placement prices. It excludes writing and other costs not included in the placement field. A catalogue update date does not establish when a publisher measured its metrics."},{title:"What should I include in my budget?",body:"Compare the placement price with available writing options, then ask the team about the agreed scope and delivery timing. A saved plan does not reserve inventory or a price."}]},
 {slug:"guest-post-vs-link-insertion",title:"Guest post vs link insertion",answer:"A guest post adds a new article to a publication; a link insertion adds a link to an existing article. Compare the surrounding content, editorial scope and disclosure before choosing a format. Confirm which format the publisher offers and what the quoted price covers, rather than assuming either option is included.",approved:false,sources:[google,spam],questions:[{title:"How do the formats differ?",body:"A new article needs a content brief and editorial review. An insertion needs an existing page with a relevant context. Publication listings do not establish that both formats are offered."},{title:"What should I confirm before choosing?",body:"Ask about the exact page or article scope, disclosure, link qualification, price and delivery timing. Check the publisher’s actual content and ask which terms apply."}],table:{columns:["Format","Content","Confirm"],rows:[["Guest post","New article","Writing and editorial scope"],["Link insertion","Existing article","Page context and availability"]]}},
 {slug:"da-vs-dr-and-traffic",title:"DA vs DR and traffic estimates",answer:"DA and DR are different third-party scores: Moz supplies Domain Authority and Ahrefs supplies Domain Rating. Traffic estimates are another signal and should be read with their provider, method and observation date. Use these measures to compare publications alongside audience relevance and editorial quality, while keeping missing values separate from zero.",approved:false,sources:[da,dr,traffic],questions:[{title:"Are DA and DR interchangeable?",body:"They come from different providers and models. Compare each score within its own system. Neither score establishes that a publication will reach your audience."},{title:"How should I read catalogue traffic?",body:"Ask for the provider and measurement date. The catalogue’s supplied traffic figures are not independently verified analytics. Ahrefs’ organic estimate uses keyword positions, search-volume estimates and estimated click-through rates; that does not identify the provider of an unspecified catalogue field."}],table:{columns:["Measure","Provider","Interpretation"],rows:[["DA","Moz","Relative authority score"],["DR","Ahrefs","Relative backlink-profile strength"],["Traffic estimate","Confirm with supplier","Estimate with method and date"]]}},
 {slug:"vet-a-guest-post-site",title:"How to vet a guest post site",answer:"Vet a guest-post site by checking its recent articles, topic relevance, editorial contacts and proposed placement scope. Compare supplied prices and metrics only after the publication makes sense for your audience. Ask for metric sources and dates, agree paid-link disclosure, and record questions about delivery and replacement terms before committing to an order.",approved:false,sources:[dr,google,spam],questions:[{title:"What should I inspect on the publication?",body:"Read recent articles and their sources. Check whether the proposed topic fits the publication, and ask who will review it. Confirm the article or page scope and the applicable terms."},{title:"Which catalogue fields can help my shortlist?",body:"Use topic, country, language, price and supplied metrics as comparison fields. Country alone does not verify audience geography, and an unavailable metric is not evidence of zero performance."}]},
 {slug:"paid-guest-posts-google-link-policies",title:"Paid guest posts and Google’s link policies",answer:"Paid guest posts need appropriate link qualification. Google recommends rel=" + '"sponsored"' + " for advertising and paid placements and also accepts nofollow. Its spam policies address links created primarily to manipulate rankings. Confirm the publisher’s disclosure and link markup before placement, and do not treat payment or a metric score as a promise of search performance.",approved:false,sources:[google,spam],questions:[{title:"How should a paid link be marked?",body:'Agree sponsored-content disclosure with the publisher. Google recommends rel="sponsored" for paid links; nofollow remains acceptable. The article’s visible disclosure and the link’s attribute address different parts of the placement.'},{title:"What should I ask the publisher?",body:"Ask how the content will be labelled and how the link will be qualified. Record the agreed scope before ordering. Search performance cannot be guaranteed by payment, format or supplied metrics."}]},
];
export function costAnswer(stats: CatalogueStatistics) {
  if (stats.minPriceCents === null || stats.maxPriceCents === null || stats.medianPriceCents === null) return "A guest post’s cost depends on the publication and agreed placement scope. The active catalogue has no price distribution available right now, so a range or median cannot be reported. Check each listing when inventory returns, and confirm writing costs, delivery timing and sponsored-link disclosure with the team before planning an order.";
  const money = (value:number) => new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:3}).format(value/100);
  return `Guest-post placement prices in this active catalogue range from ${money(stats.minPriceCents)} to ${money(stats.maxPriceCents)}, with a median of ${money(stats.medianPriceCents)} across ${stats.total.toLocaleString("en-US")} publications. These are supplied USD placement prices, not a full campaign quote. Writing may cost extra where available; compare audience fit and confirm scope and disclosure before choosing a publisher.`;
}
