import { randomUUID } from "node:crypto";
import type { Filter, ClientSession } from "mongodb";
import { ApiError } from "@/lib/api";
import { store, recordTransaction } from "@/lib/db";
import { logAudit } from "@/lib/audit";
import { canAccess, canEdit, canPublish } from "@/lib/security/permissions";
import {
  collections,
  type CmsRecord,
  type Collection,
  type RecordInput,
  type UserSummary,
} from "./types";
import { validateRecord } from "./validation";
import { invalidate } from "./invalidation";
export { invalidate } from "./invalidation";

export function collectionName(value: string): Collection {
  if (!collections.includes(value as Collection))
    throw new ApiError(404, "Collection not found.");
  return value as Collection;
}
export function queryOptions(
  request: Request,
  allowedSort: readonly string[] = ["updatedAt", "createdAt", "title"],
) {
  const params = new URL(request.url).searchParams;
  const q = (params.get("q") || "").slice(0, 150);
  const page = Math.max(1, Math.min(100000, Number(params.get("page")) || 1));
  const pageSize = Math.max(
    1,
    Math.min(100, Number(params.get("pageSize")) || 20),
  );
  const sort = allowedSort.includes(params.get("sort") || "")
    ? params.get("sort")!
    : allowedSort[0];
  const direction = params.get("direction") === "asc" ? 1 : -1;
  const status = (params.get("status") || "").slice(0, 50);
  return {
    q,
    page: Math.floor(page),
    pageSize: Math.floor(pageSize),
    sort,
    direction,
    status,
  };
}
export function escapeRegex(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
export async function listRecords(
  collection: Collection,
  request: Request,
  user: UserSummary,
) {
  if (!canAccess(user, collection))
    throw new ApiError(403, "You cannot view this collection.");
  const { records } = await store();
  const options = queryOptions(request);
  const filter: Filter<CmsRecord> = { collection };
  if (user.role === "author") filter.ownerId = user.id;
  if (options.status) filter.status = options.status;
  if (options.q)
    filter.$or = [
      { title: { $regex: escapeRegex(options.q), $options: "i" } },
      { slug: { $regex: escapeRegex(options.q), $options: "i" } },
    ];
  const [data, total] = await Promise.all([
    records
      .find(filter, { projection: { _id: 0 } })
      .sort({ [options.sort]: options.direction as 1 | -1, id: 1 })
      .skip((options.page - 1) * options.pageSize)
      .limit(options.pageSize)
      .toArray(),
    records.countDocuments(filter),
  ]);
  return { data, total, page: options.page, pageSize: options.pageSize };
}
export async function getRecord(
  collection: Collection,
  id: string,
  user: UserSummary,
) {
  if (!canAccess(user, collection))
    throw new ApiError(403, "You cannot view this collection.");
  const record = await (
    await store()
  ).records.findOne({ id, collection }, { projection: { _id: 0 } });
  if (!record || (user.role === "author" && record.ownerId !== user.id))
    throw new ApiError(404, "Record not found.");
  return record;
}
export async function validated(
  collection: Collection,
  input: unknown,
  excludeId?: string,
  session?: ClientSession,
) {
  const existing = await (
    await store()
  ).records
    .find({}, { projection: { _id: 0 }, session })
    .toArray();
  try {
    return validateRecord(collection, input, existing, excludeId);
  } catch (error) {
    if (error instanceof Error && error.name !== "ZodError")
      throw new ApiError(422, error.message);
    throw error;
  }
}
function requireWrite(
  user: UserSummary,
  collection: Collection,
  input: RecordInput,
  old?: CmsRecord,
) {
  if (!canAccess(user, collection) || (old && !canEdit(user, old)))
    throw new ApiError(403, "You cannot edit this record.");
  if (
    collection === "content" &&
    ["published", "scheduled"].includes(input.status) &&
    !canPublish(user)
  )
    throw new ApiError(
      403,
      "Only editors and admins can publish or schedule content.",
    );
  if (user.role === "author" && !["draft", "archived"].includes(input.status))
    throw new ApiError(403, "Authors can save only their own drafts.");
  if (collection === "media" && !old)
    throw new ApiError(422, "Use the media upload endpoint to create media.");
  if (collection === "notFound" && !old)
    throw new ApiError(
      422,
      "404 logs are generated by public requests in Phase 4.",
    );
}
export async function createRecord(
  collection: Collection,
  raw: unknown,
  user: UserSummary,
) {
  const record = await recordTransaction(async (session) => {
    const input = await validated(collection, raw, undefined, session);
    requireWrite(user, collection, input);
    if (
      collection === "content" &&
      input.status === "published" &&
      !input.data.publishedAt
    )
      input.data.publishedAt = new Date().toISOString();
    const now = new Date().toISOString();
    const next: CmsRecord = {
      ...input,
      id: randomUUID(),
      collection,
      ownerId: user.id,
      version: 1,
      createdAt: now,
      updatedAt: now,
    };
    await (await store()).records.insertOne(next, { session });
    await logAudit(user.id, "create", collection, next.id, next.title, session);
    return next;
  });
  invalidate(collection, record.slug);
  return record;
}
export async function updateRecord(
  collection: Collection,
  id: string,
  raw: unknown,
  user: UserSummary,
) {
  const old = await getRecord(collection, id, user);
  const { records, revisions } = await store();
  const record = await recordTransaction(async (session) => {
    const input = await validated(collection, raw, id, session);
    requireWrite(user, collection, input, old);
    if (
      collection === "content" &&
      input.status === "published" &&
      !input.data.publishedAt
    )
      input.data.publishedAt = new Date().toISOString();
    if (input.version !== old.version)
      throw new ApiError(
        409,
        "This record changed elsewhere. Reload before saving.",
      );
    const record: CmsRecord = {
      ...old,
      ...input,
      version: old.version + 1,
      updatedAt: new Date().toISOString(),
    };
    const result = await records.replaceOne(
      { id, collection, version: old.version },
      record,
      { session },
    );
    if (!result.modifiedCount)
      throw new ApiError(
        409,
        "This record changed elsewhere. Reload before saving.",
      );
    await revisions.insertOne(
      {
        id: randomUUID(),
        recordId: id,
        version: old.version,
        snapshot: old,
        actorId: user.id,
        createdAt: new Date().toISOString(),
      },
      { session },
    );
    await logAudit(user.id, "update", collection, id, record.title, session);
    return record;
  });
  invalidate(collection, old.slug);
  invalidate(collection, record.slug);
  return record;
}
export async function archiveRecord(
  collection: Collection,
  id: string,
  user: UserSummary,
) {
  const old = await getRecord(collection, id, user);
  if (!canEdit(user, old))
    throw new ApiError(403, "You cannot archive this record.");
  return updateRecord(
    collection,
    id,
    { ...old, status: "archived", version: old.version },
    user,
  );
}
export async function duplicateRecord(
  collection: Collection,
  id: string,
  user: UserSummary,
) {
  const old = await getRecord(collection, id, user);
  if (collection !== "content")
    throw new ApiError(422, "Only content can be duplicated.");
  const copy = {
    title: `${old.title} (copy)`,
    slug: `${old.slug}-copy-${randomUUID().slice(0, 6)}`,
    status: "draft",
    data: { ...old.data, publishedAt: null, scheduledAt: null },
  };
  return createRecord(collection, copy, user);
}
